### PR TITLE
Removed Software Engineering

### PR DESCRIPTION
**Pull request by chriswolfdesign**
Hey Forrest,

I think it's really awesome that you're doing this!  Sadly, UBC no longer offers their TypeScript Software Engineering course on EDX :(.  However, I did find a university that offers a two part course in Saas/Software Engineering together.  I'd be happy to add these courses if you'd like.  I'll also open this as an issue in case you prefer to see suggestions that way.

### CODE REVIEW

**Comment by Elpuma** [comment]
Software Engineering is still available on edX as of this very moment unless I'm missing something 
image

**Comment by chriswolfdesign** [comment]
You can sign up for it and see it on their catalogue.  But once you sign up, you can't actually access the materials.  It says the course stopped allowing audited students in January.  Been having this issue with a lot of courses on edx lately.

**Comment by flyingsl0ths** [comment]
I'm currently auditing the course no problem

**Comment by chriswolfdesign** [comment]
That's odd. I'll look into it further. Sorry about that.

**Pull request closed without merging**
