### PR TITLE
I made a flowchart for the project

### PR DESCRIPTION
**Pull request by davidhuang620**
Hi Forrest Knight,

I appreciate you put together such an amazing free resource for computer science courses. 
There are many different prerequisites for different courses so that I made a flowchart for users to have an easier time guiding through the whole degree plan.

I tried to just attach the pdf file, but GitHub cannot display hyperlinks from the pdf properly so that I added the link to the flowchart in the README file.

Thanks,
David

### CODE REVIEW

**Comment by knyzorg** [comment]
Looks super nice. Could you remove the linksynergy stuff though?

**Comment by davidhuang620** [comment]
Hi knyzorg,

Can you explain more about the linksynergy stuff? 
Do you mean the underline of the hyperlinks? or the pointers between classes?

**Comment by knyzorg** [comment]
All the links are redirected through some weird click.linksynergy thing. I know the master branch is full of it, but it’d be nice to have a pdf without them

**Comment by davidhuang620** [comment]
I see what you are talking about. It should be fixed now.

**Comment by AlexMunoz905** [comment]
Thanks @davidhuang620 . Looks real nice.

**Pull request closed without merging**
